name: Cross compile grpcwebproxy

on:
  workflow_dispatch:

jobs:
  grpcwebproxy:

    name: Cross compile grpcwebproxy

    runs-on: ubuntu-20.04

    env:
      workdir: ./grpcwebproxy-source

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 1

      - name: Git clone grpcwebproxy
        run: |
          git clone https://github.com/improbable-eng/grpc-web.git ${{ env.workdir }}
          cp ./.github/grpcwebproxy-releaser.yml ${{ env.workdir }}/.goreleaser.yml

      - name: Set up GoReleaser
        uses: actions/setup-go@v4.1.0
        with:
          go-version: "1.21"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          distribution: goreleaser
          workdir: ${{ env.workdir }}
          version: latest
          args: release --rm-dist --snapshot
            
      - name: Release binaries 
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: grpcwebproxy
          files: ${{ env.workdir }}/dist/*.tar.gz